### ISSUE TITLE
系统配置

### ISSUE THREAD

**Issue by ForestCao** [incubate-leon/course#1]
将你当前电脑的硬件配置信息填入下表中的“当前配置”一栏：

组件 | 推荐配置 | 当前配置
-- | -- | --
计算机型号 | （无要求） | （PC组装机写主板型号）
CPU | Intel i5+ | （比如i9-9900k）
RAM | 8G+ | （比如32G DDR4）
HDD | 固态240G+ |  
GPU | （无要求） |  
NIC | （无要求） | （填写有线网卡型号）
Wi-Fi | （无要求）

参考 [《系统管理1：系统配置》](https://github.com/incubate-leon/course/wiki/system#1-%e7%b3%bb%e7%bb%9f%e9%85%8d%e7%bd%ae)

**Comment by chan-leon** [comment]
组件 | 推荐配置 | 当前配置
-- | -- | --
计算机型号 |(无要求)| Inspiron 15-7560|
CPU | Intel i5+ | intel Core i7
RAM | 8G+ | 8G
HDD | 固态240G+ |  固态128
GPU | （无要求） |  Intel HD Graphics 620
NIC | （无要求） | （填写有线网卡型号）
Wi-Fi | （无要求）

**Comment by ForestCao** [comment]
> 组件	推荐配置	当前配置
> 计算机型号	(无要求)	Inspiron 15-7560
> CPU	Intel i5+	intel Core i7
> RAM	8G+	8G
> HDD	固态240G+	 固态128
> GPU	（无要求）	 Intel HD Graphics 620
> NIC	（无要求）	（填写有线网卡型号）
> Wi-Fi	（无要求）

Approve
