### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by ForestCao** [incubate-leon/course#2]
练习表格中的命令，附上history
参考 [《系统管理2：shell》](https://github.com/incubate-leon/course/wiki/system#2-shell)

**Comment by chan-leon** [comment]
40  cat hello.sh
   41  mv hello.sh hello.py
   42  ls
   43  mv demo demo01
   44  ls
   45  cp hello.py max.py
   46  ls
   47  cp -r demo01 demo02
   48  ls
   49  rm max.py
   50  rm -r max.py
   51  rm demo02
   52  rm -r demo02
   53  ls
   54  history
   55  history |cbcopy

**Comment by ForestCao** [comment]
> 40 cat hello.sh
> 41 mv hello.sh hello.py
> 42 ls
> 43 mv demo demo01
> 44 ls
> 45 cp hello.py max.py
> 46 ls
> 47 cp -r demo01 demo02
> 48 ls
> 49 rm max.py
> 50 rm -r max.py
> 51 rm demo02
> 52 rm -r demo02
> 53 ls
> 54 history
> 55 history |cbcopy

Approve

**Comment by conke** [comment]
```shell
40 cat hello.sh
41 mv hello.sh hello.py
42 ls
43 mv demo demo01
44 ls
45 cp hello.py max.py
46 ls
47 cp -r demo01 demo02
48 ls
49 rm max.py
50 rm -r max.py
51 rm demo02
52 rm -r demo02
53 ls
54 history
55 history |cbcopy
```

**Comment by chan-leon** [comment]
```  
  720  code
  721  number = [1,2,3,4,5]
  722  python
  723  code
  724  code
  725  echo "hello,world"
  726  echo "this home is $HOME"
  727  echo "print ("hello,world")"> hello.py
  728  cat hello.py
  729  man mkdir
  730  ls
  731  ls *.sh
  732  ls*.py
  733  ls *.py
  734  pwd
  735  cd /
  736  cd /$HOME
  737  cat hello.py
  738  mv world.sh hello.sh
  739  ls
  740  mv demo demo01
  741  cp hello.py max.py
  742  ls
  743  cp -r demo01 demo02
  744  ls
  745  rm max.py
  746  rm -r demo02
  747  ls
  748  history
  749  history | pbcopy -20
```
