### ISSUE TITLE
包管理 (CLI版App Store)

### ISSUE THREAD

**Issue by ForestCao** [incubate-leon/course#3]
执行如下命令，粘贴回复结果

macOS:

`$ brew list -version | pbcopy`

Windows:

`$ choco list -l | clip`

参考 [《系统管理3：包管理》](https://github.com/incubate-leon/course/wiki/system#3-%e5%8c%85%e7%ae%a1%e7%90%86-cli%e7%89%88app-store)

**Comment by chan-leon** [comment]
brew下载：
python 3.7.4_1
vscode
迅雷下载：
virtualbox
vagrant
vagrant-manager
vmware-fusion
iterm2

**Comment by chan-leon** [comment]
brew下载：
1. python 3.7.4_1
1. vscode

迅雷下载：
1. virtualbox
1. vagrant
1. vagrant-manager
1. vmware-fusion
1. iterm2
