### ISSUE TITLE
 开发环境

### ISSUE THREAD

**Issue by ForestCao** [incubate-leon/course#4]
运行一个简单的Python程序，截图回复

参考 [《系统管理4：开发环境》](https://github.com/incubate-leon/course/wiki/system#4-%e5%bc%80%e5%8f%91%e7%8e%af%e5%a2%83)

**Comment by chan-leon** [comment]
![Screen Shot 2019-10-16 at 12 13 30](https://user-images.githubusercontent.com/56581620/66887694-610d9800-f00e-11e9-8fbc-703b350cae5a.png)

**Comment by chan-leon** [comment]
![Screen Shot 2019-10-16 at 12 26 02](https://user-images.githubusercontent.com/56581620/66888182-21e04680-f010-11e9-9b63-6bc7ec63da99.png)
