### ISSUE TITLE
虚拟机

### ISSUE THREAD

**Issue by ForestCao** [incubate-leon/course#5]
执行如下命令，粘贴回复结果
`$ vagrant box list | pbcopy # macOS`

`$ vagrant box list | clip # Windows`

参考 [《系统管理5：虚拟机》](https://github.com/incubate-leon/course/wiki/system#5-%e8%99%9a%e6%8b%9f%e6%9c%ba)

**Comment by chan-leon** [comment]
archlinux/archlinux (virtualbox, 0)
